name: Pipeline
run-name: deploy in live
on:

  push:
    branches:
      - main
   
  pull_request:
    branches:
      - main
    paths:
      - "*.md"

jobs:
  jobs1:
    environment: 
      name: developer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.1

      - name: Print message
        run: echo "Hello, Algo-${{vars.NAME}}-Máss!"

      - name: echo secreto
        run: echo ${{secrets.SECRETO}} > secret.txt

      - name: Echo file
        run: cat secret.txt

  

   
  jobs2: 
    environment: 
      name: production
    needs: jobs1
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v6.0.1

      - name: Print message
        run: echo "Hello, Algo-${{vars.NAME}}-Máss!"

      - name: echo secreto
        run: echo ${{secrets.SECRETO}} > secret.txt

      - name: Echo file
        run: cat secret.txt
  
  jobs3: 
      
    needs: jobs2
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v6.0.1

      - name: Print message
        run: echo "Hello, Algo-${{vars.NAME}}-Máss!"

     

