name: Pipeline
run-name: deploy in live
on:

  push:
    branches:
      - main
   
  pull_request:
    branches:
      - main
    paths:
      - "*.md"

jobs:
  jobs1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.1

      - name: List files
        run: ls -la

      - name: Print message
        run: echo "Hello, Algo-${{vars.NAME}}-MÃ¡ss!"

      - name: echo secreto
        run: echo ${{secrets.SECRETO}} > secret.txt

      - name: Echo file
        run: cat secret.txt

  

   
  jobs2: 
    needs: jobs1
    runs-on: ubuntu-latest
    steps:
      - name: Print message jobs2
        run: echo "Hello, World! jobs2"

